### ISSUE TITLE
Use "merge" instead of "deepmerge"

### ISSUE THREAD

**Issue by ThomasFett** [webdriverio/cucumber-boilerplate#1]
I would suggest to use "merge" rather than the "deepmerge" module when merging `config.js` and `config.whatever.js` in `test/support/configure.js`, since deepmerge combines arrays instead of replacing them.

This leads to an array consisting of `'test/features/**/*.feature'` from the default file + `'test/features/whatever1.feature', 'test/features/whatever2.feature', 'test/features/whatever3.feature', ...` that you add in the specific configuration file.

I guess this is never what you want.

Is there any drawback in not using the "deepmerge" module?

**Comment by christian-bromann** [comment]
[Merging arrays](https://github.com/KyleAMathews/deepmerge/blob/master/index.js#L15-L28) is definitely not desired here. I guess we need an own merge method then.

**Comment by ThomasFett** [comment]
This module works for me: [https://github.com/yeikos/js.merge](https://github.com/yeikos/js.merge)

All object properties are combined correctly and arrays are fully substituted by the second object (and not merged). 

I would suggest to use this one instead.

**Comment by christian-bromann** [comment]
This got obsolete with recent update.
