### ISSUE TITLE
I followed your instructions and when I ran the results correctly, but when I checked my website with the phantomjs, it did not find elements in the my website and chrome everything passed. Can you explain me?

### ISSUE THREAD

**Issue by Hunghbm** [webdriverio/cucumber-boilerplate#111]
# Issue description
> Please provide a brief description of the problem you are experiencing

# Steps to reproduce
> How can you reproduce the issue you are facing?

# Expected behavior
> What did you expect to happen?

# Actual behavior
> What did happen?

# Issue occurred on browser/platform 
> What platform did you experience this issue on? If you tested multiple browsers/platforms please add them, if you did not experience the issue on other tested browsers or platforms note it as well.

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
