### ISSUE TITLE
not able to run single feature using either --tags or --spec

### ISSUE THREAD

**Issue by achavva** [webdriverio/cucumber-boilerplate#115]
# Issue description
> Please provide a brief description of the problem you are experiencing

# Steps to reproduce
> How can you reproduce the issue you are facing?

# Expected behavior
> What did you expect to happen?

# Actual behavior
> What did happen?

# Issue occurred on browser/platform 
> What platform did you experience this issue on? If you tested multiple browsers/platforms please add them, if you did not experience the issue on other tested browsers or platforms note it as well.

**Comment by achavva** [comment]
not able to run feature using --tags or --spec

**Comment by christian-bromann** [comment]
See https://github.com/webdriverio/cucumber-boilerplate#using-tags. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by achavva** [comment]
Hi christian, I followed the readme document but I am not able to run single feature using --tags. Any other place to be modified.
Command I used :::   yarn run wdio -- --specs ./src/features/google1.feature

**Comment by achavva** [comment]
Sorry christian, I typo in the above comment it is --specs
Even I am not able to run using --tags
I am getting error as "The system cannot find the path specified".

**Comment by wvankuipers** [comment]
See https://github.com/webdriverio/cucumber-boilerplate#using-tags. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

(locking further conversation)
