### ISSUE TITLE
'Step Definitions not Defined' exception when Cucumber 2.3.1 installed

### ISSUE THREAD

**Issue by saundap** [webdriverio/cucumber-boilerplate#126]
# Issue description
'Step Definitions not Defined' exception when Cucumber 2.3.1 installed
I found that if I updated the Step Definition syntax with the format from the cucumber-js github site (https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/step_definitions.md), then the wdio cucumber framework could carry on and execute the targeted scenario.

Cucumber 2.3.1 appears to be the version identified within the frameworks package.json file - so webdriverio itself is configured for the latest cucumber-js, but this boilerplate scenario doesn't seem have kept pace - I could be mistaken and missing something fundamental.

# Steps to reproduce
Load the scenarios and execute using the wdio cucumber framework setup whilst having the latest cucumber 2.3.1 installed. 

# Expected behavior
Execution of a sample Cucumber test using the supplied features and steps results in a successful test run.

# Actual behavior
Execution of a sample Cucumber test using the supplied features and steps results in a 'Step Definition not defined' exception.

# Issue occurred on browser/platform 
Occurs on Windows platform, agnostic to which browser is utilised.

**Comment by wvankuipers** [comment]
Fixed in v1.3.0
