### ISSUE TITLE
What selector types can be used?

### ISSUE THREAD

**Issue by karl0ss** [webdriverio/cucumber-boilerplate#132]
I am trying to click a link using "When I click on the link "a[href*=TOPSHOP]""

This is giving me the error that it does not exist on the page, but if I use chrome on the same page, the link can be found, I thought this framework should be able to use css selectors?

Thanks

**Comment by wvankuipers** [comment]
Can you try the following:

    When I click on the element "a[href*=TOPSHOP]"

And let me know if that works? It seems that the link version of the [clickElement action uses a `=` prefix for the selector.](https://github.com/webdriverio/cucumber-boilerplate/blob/master/src/support/action/clickElement.js#L15)

**Comment by karl0ss** [comment]
Sorry, I looked at the examples, and this became apparent to me...sorry for wasting your time.
