### ISSUE TITLE
All tests fail

### ISSUE THREAD

**Issue by luckylooke** [webdriverio/cucumber-boilerplate#134]
# Issue description
> running basic command after installation "How to run tests", all tests fails

# Steps to reproduce
> fresh install of the project (git clone ..)
> cleaning omitted (yarn run clean)
> yarn install
> yarn run local-webserver
> new terminal tab
> yarn run wdio

# Expected behavior
> all tests to success

# Actual behavior
> all tests fail

# Issue occurred on browser/platform 
> System:
    Node       : v6.9.5
    OS         : macOS Sierra

<img width="415" alt="screenshot at sep 08 13-38-34" src="https://user-images.githubusercontent.com/3660030/30210040-0a5e471e-949b-11e7-83a7-7a63796cab9a.png">

**Comment by wvankuipers** [comment]
Please add cucumber 1.x to the dependency list of the project. This issue will be resolved in 1.3.0.

**Comment by leifoolsen** [comment]
I think this is connected to wdio-cucumber-framework-1.0.2. If I downgrade to wdio-cucumber-framework-0.3.1 the tests works.

**Comment by wvankuipers** [comment]
This will be resolved once #129 get's merged (releasing version 1.3.0 of the boilerplate)
