### ISSUE TITLE
browser.keys(key) does not work in firefox

### ISSUE THREAD

**Issue by YYSU** [webdriverio/cucumber-boilerplate#136]
# Issue description
When I run the `myFirstTest.feature` for a test in firefox, I got an error because of `I press "Enter"`.
<img width="1141" alt="2017-09-12 10 41 57" src="https://user-images.githubusercontent.com/12994810/30305762-2ab95e9a-97a7-11e7-9006-0d78dae07f22.png">

# Steps to reproduce
just send keys in firefox

# Expected behavior
send the "enter" key, and continue with other steps. 

# Actual behavior
an error `sendKeysToActiveElement` 

# Issue occurred on browser/platform 
browser: `firefox`, version: `55.0.3 (64 bits)`
platform: `Mac OS X 10.12.6`
geckodriver version: `0.18.0`

**Comment by christian-bromann** [comment]
Firefox doesn't support this command anymore. We will provide a replacement with the action API command soon.

**Comment by AliF50** [comment]
@christian-bromann What is the solution? I am stuck with this issue at the moment as well.

**Comment by christian-bromann** [comment]
use http://webdriver.io/api/protocol/actions.html
