### ISSUE TITLE
Missing tests for select.feature will run into error

### ISSUE THREAD

**Issue by silkentrance** [webdriverio/cucumber-boilerplate#140]
# Issue description
~~When running the script 'npm run test:features' then the tests for the select.feature will fail.~~
Vital tests are missing for that feature, namely selectByValue/Attribute/Index/Text using XPath selectors.

# Steps to reproduce
First you need to clone the repo and then npm install and npm install --save-dev cucumber (either version 2.3.1 or latest version 3.0.2, both will work just fine).
```
npm run test:features
```
~~See https://gist.github.com/silkentrance/14827c7d10809fa6ae4d654f6aab9a97 for a log.~~

# Expected behavior
The missing tests should be implemented and run without error.

# Actual behavior
Some of the currently missing tests will run into error.

# Issue occurred on browser/platform 
phantomjs

**Comment by silkentrance** [comment]
I can provide you with a PR for the missing tests.

**Comment by christian-bromann** [comment]
@silkentrance that would be fantastic

**Comment by silkentrance** [comment]
@christian-bromann With the latest version from the repository, the existing tests no longer fail. I am updating the description accordingly.

**Comment by christian-bromann** [comment]
Let's continue the conversation in #141
