### ISSUE TITLE
number or type of arguments don't agree with elementIdClick protocol command error while running on firefox

### ISSUE THREAD

**Issue by vibskant007** [webdriverio/cucumber-boilerplate#147]
# Issue description
> When I am trying to click an element it gives me  number or type of arguments don't agree with elementIdClick protocol command

# Steps to reproduce
> number or type of arguments don't agree with elementIdClick protocol command
running firefox
Error: number or type of arguments don't agree with elementIdClick protocol command
    at World.module.exports (src/support/action/clickElement.js:24:5)
    at Promise.F (node_modules/wdio-sync/node_modules/core-js/library/modules/_export.js:35:28)
    at elementIdClick() - click.js:20:22

# Expected behavior
> The same method works with chrome

# Actual behavior
> What did happen?

# Issue occurred on browser/platform 
> Firefox,macOX

**Comment by christian-bromann** [comment]
@vibskant007 please provide a reproducible example and logs otherwise we can't help you!

**Comment by vibskant007** [comment]
08:03:12.059 INFO - /status: Executing GET on /status (handler: Status)
08:03:17.062 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@75b19a72
08:03:17.063 INFO - /status: Executing GET on /status (handler: Status)
08:03:19.492 INFO - Binding default provider to: org.openqa.selenium.chrome.ChromeDriverService
08:03:19.492 INFO - Found handler: org.openqa.selenium.remote.server.BeginSession@6a2967c0
08:03:19.492 INFO - /session: Executing POST on /session (handler: BeginSession)
08:03:19.493 INFO - Capabilities are: Capabilities {rotatable=true, locationContextEnabled=true, loggingPrefs={browser=ALL, driver=ALL, }, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, maxInstances=5.0, requestOrigins={url=http://webdriver.io, version=4.6.2, name=webdriverio, }, }
08:03:19.493 INFO - Capabilities {rotatable=true, locationContextEnabled=true, loggingPrefs={browser=ALL, driver=ALL, }, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, maxInstances=5.0, requestOrigins={url=http://webdriver.io, version=4.6.2, name=webdriverio, }, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.firefox.GeckoDriverService)
08:03:19.493 INFO - Capabilities {rotatable=true, locationContextEnabled=true, loggingPrefs={browser=ALL, driver=ALL, }, browserName=firefox, javascriptEnabled=true, handlesAlerts=true, maxInstances=5.0, requestOrigins={url=http://webdriver.io, version=4.6.2, name=webdriverio, }, } matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
1507795399496	geckodriver	INFO	geckodriver 0.18.0
1507795399499	geckodriver	INFO	Listening on 127.0.0.1:7263
1507795399627	geckodriver::marionette	INFO	Starting browser /usr/bin/firefox with args ["-marionette"]
1507795400272	Marionette	INFO	Enabled via --marionette
1507795401867	Marionette	INFO	Listening on port 35140
JavaScript error: chrome://marionette/content/server.js, line 337: NS_ERROR_SOCKET_ADDRESS_IN_USE: Component returned failure code: 0x804b0036 (NS_ERROR_SOCKET_ADDRESS_IN_USE) [nsIServerSocket.initSpecialConnection]
1507795401972	Marionette	DEBUG	loaded listener.js
08:03:22.066 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@6ae0c93
08:03:22.067 INFO - /status: Executing GET on /status (handler: Status)
08:03:23.623 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:23.624 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing POST on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/url (handler: ServicedSession)
1507795403631	Marionette	DEBUG	Received DOM event "beforeunload" for "about:blank"
1507795404153	Marionette	DEBUG	Received DOM event "pagehide" for "about:blank"
1507795404153	Marionette	DEBUG	Received DOM event "unload" for "about:blank"
1507795404184	Marionette	DEBUG	Received DOM event "pageshow" for "http://www.hotstar.com/"
08:03:24.304 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:24.304 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing POST on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/window/current/size (handler: ServicedSession)
08:03:27.070 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@37ed0e81
08:03:27.070 INFO - /status: Executing GET on /status (handler: Status)

08:03:32.073 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@23215e06
08:03:32.074 INFO - /status: Executing GET on /status (handler: Status)
08:03:37.077 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@441aed78
08:03:37.077 INFO - /status: Executing GET on /status (handler: Status)
08:03:39.508 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:39.509 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing POST on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/elements (handler: ServicedSession)
08:03:39.593 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:39.593 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing POST on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/element (handler: ServicedSession)
08:03:39.745 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:39.745 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing GET on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/screenshot (handler: ServicedSession)
08:03:42.080 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@d1acda7
08:03:42.080 INFO - /status: Executing GET on /status (handler: Status)
08:03:42.377 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:42.377 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing POST on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/elements (handler: ServicedSession)
08:03:42.517 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:42.518 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing POST on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/elements (handler: ServicedSession)
08:03:42.693 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:42.693 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing POST on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/elements (handler: ServicedSession)
08:03:42.773 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:42.773 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing POST on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/element (handler: ServicedSession)
08:03:42.850 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:42.850 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing GET on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/screenshot (handler: ServicedSession)
08:03:45.006 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:45.006 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing POST on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/elements (handler: ServicedSession)
08:03:45.088 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:45.088 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing POST on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/element (handler: ServicedSession)
08:03:45.169 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:45.169 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing GET on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75/screenshot (handler: ServicedSession)
08:03:47.083 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@56dcf026
08:03:47.084 INFO - /status: Executing GET on /status (handler: Status)
08:03:47.460 INFO - Found handler: org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:47.461 INFO - Handler thread for session b9c5b114-d2b0-400c-bb43-e6d156db9f75 (firefox): Executing DELETE on /session/b9c5b114-d2b0-400c-bb43-e6d156db9f75 (handler: ServicedSession)
1507795427465	Marionette	INFO	New connections will no longer be accepted
[Child 18545] WARNING: pipe error (32): Connection reset by peer: file /home/worker/workspace/build/src/ipc/chromium/src/chrome/common/ipc_channel_posix.cc, line 353
08:03:47.593 INFO - Removing session org.openqa.selenium.remote.server.ServicedSession@3ccb0125
08:03:52.087 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@d232aee
08:03:52.087 INFO - /status: Executing GET on /status (handler: Status)
08:03:57.090 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@4217cae1
08:03:57.090 INFO - /status: Executing GET on /status (handler: Status)
08:04:02.094 INFO - Found handler: org.openqa.selenium.remote.server.commandhandler.Status@361b767a
08:04:02.094 INFO - /status: Executing GET on /status (handler: Status)

**Comment by vibskant007** [comment]
number or type of arguments don't agree with elementIdClick protocol command
[firefox #0-0] Error: number or type of arguments don't agree with elementIdClick protocol command
[firefox #0-0]     at World.module.exports (src/support/action/clickElement.js:24:5)
[firefox #0-0]     at Promise.F (node_modules/wdio-sync/node_modules/core-js/library/modules/_export.js:35:28)
[firefox #0-0]     at elementIdClick() - click.js:20:22

**Comment by vibskant007** [comment]
I have sel hub running at java -Dwebdriver.gecko.driver=/home/ubuntu/geckodriver -Dmarionette=false -jar selenium-server-standalone-3.5.0.jar -role node -hub

But the same works with chrome perfectly

**Comment by vibskant007** [comment]
I click on the element "a.signin.ng-click"
This works with chrome but with firefox fails.

**Comment by tomchin23** [comment]
I am getting this same error on Firefox and Internet Explorer.  On Chrome my tests run fine.

**Comment by tomchin23** [comment]
I updated to the latest version of webdriver `"webdriverio": "^4.9.10"` and now tests are working in Chrome, Firefox, and Internet Explorer
