### ISSUE TITLE
support to add random value to input field... 

### ISSUE THREAD

**Issue by vibskant007** [webdriverio/cucumber-boilerplate#148]
# Issue description
> Please provide a brief description of the problem you are experiencing

# Steps to reproduce
> How can you reproduce the issue you are facing?

# Expected behavior
> What did you expect to happen?

# Actual behavior
> What did happen?

# Issue occurred on browser/platform 
> What platform did you experience this issue on? If you tested multiple browsers/platforms please add them, if you did not experience the issue on other tested browsers or platforms note it as well.

**Comment by christian-bromann** [comment]
This issue post is really bad. If you have any feature request please provide an comprehensive description for it.

**Comment by vibskant007** [comment]
Feature description 
And I set "**random value here**" to the inputfield ".//input[@id='email']//preceding::input[2]"

is this feature available with steps?

**Comment by christian-bromann** [comment]
Yes, you just need to have a proper regex match and your steps replaces it with a random number. Please join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you have further questions.
