### ISSUE TITLE
tagExpression doesn't allow to add more than one tag.

### ISSUE THREAD

**Issue by arunaousula9421** [webdriverio/cucumber-boilerplate#153]
Hi, Below is my CucumberOptns where I am passing the tags to run specific tests

```
cucumberOpts: {
        require: ['./src/step_definitions/loginSteps.ts', './src/step_definitions/searchSteps.ts', './src/support/hook.js'],        // <string[]> (file/dir) require files before executing features
        backtrace: false,   // <boolean> show full backtrace for errors
        compiler: ["ts:ts-node/register"],       // <string[]> ("extension:module") require files with the given EXTENSION after requiring MODULE (repeatable)
        dryRun: false,      // <boolean> invoke formatters without executing steps
        failFast: false,    // <boolean> abort the run on first failure
        format: ['pretty'], // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
        colors: true,       // <boolean> disable colors in formatter output
        snippets: true,     // <boolean> hide step definition snippets for pending steps
        source: true,       // <boolean> hide source uris
        profile: [],        // <string[]> (name) specify the profile to use
        strict: false,      // <boolean> fail if there are any undefined or pending steps
        tags: [],
        tagExpression: '@login,@search',           // <string[]> (expression) only execute the features or scenarios with tags matching the expression
        timeout: 20000,     // <number> timeout for step definitions
        ignoreUndefinedDefinitions: true, // <boolean> Enable this config to treat undefined definitions as warnings.
    },
```
For Example, I have two feature files with tags **@login** and **@search**. If I add only one tag which is **@login** it spins up two instances where in one instance it doesn't run the tests and in the second instance it runs the tests for the **@login**. Actually it should spawn up  only one instance. As I have two features it spawn 2 instances.

In the other situation as above in the **cucumberOpts**, if I pass two tags it spawn two instances and didn't run both the tests. Skipped both of them.

Tried adding different combinations of tag expression.
For example: if I add **@login not @search**, it does same as above open two instances and run one test[**@login**] and in another instance launches browser and doesn't run anything[**@search**].

And if I add **@login and search**, it launches instances for both and skips the tests.

Can I please know if this how it behaves.

**Comment by wvankuipers** [comment]
Hello @arunaousula9421 ,

It appears you are using an older version of the boilerplate. If you update to [the latest version](https://github.com/webdriverio/cucumber-boilerplate/tree/v1.3.1) you can use the tags [as described here](https://docs.cucumber.io/tag-expressions/)

**Comment by arunaousula9421** [comment]
@wvankuipers tags works as expected but the problem is when I have two feature files with tags @login and @search. If I add only one tag which is @login it spins up two instances where in one instance it doesn't run the tests and in the second instance it runs the tests for the @login. Actually it should spawn up only one instance. As I have two features it spawn 2 instances.

**Comment by wvankuipers** [comment]
This is a know bug in WDIO (-cucumber-framework) https://github.com/webdriverio/webdriverio/issues/1247

**Comment by RobbieDixonSMS** [comment]
I resolved this issue by containing my argument in triple double quotes:

**npx wdio wdio.conf.js --cucumberOpts.tagExpression """@smoke or @sanity"""**

My source is here:

https://www.npmjs.com/package/@wdio/cucumber-framework?activeTab=readme
