### ISSUE TITLE
Checking Text on Buttons doesn't work as intended

### ISSUE THREAD

**Issue by glenheide** [webdriverio/cucumber-boilerplate#155]
### Issue description
When I ran the step `And the element "button[id='test']" contains the text "Test"`, the test kept failing. The full error I get back is `expected '' to include 'Test'`.

When I debugged the code, I found that [this line of code](https://github.com/webdriverio/cucumber-boilerplate/blob/master/src/support/check/checkContainsText.js#L15) doesn't work well with buttons. For a button element, `getValue` returns an empty string `''` instead of a null, so it won't use `getText` which actually does return the proper value of `"Test"` in my case.

As a quick fix, I just changed it to the following and it worked:
```
if ((browser.getAttribute(element, 'value') === null) || (browser.getAttribute(element, 'type') === 'button')) {
    command = 'getText';
}
```
I'm not sure if it's the best fix or if there's a better way, but it worked well enough for me. The other "check text" files likely suffer from the same issue as well.

### Issue occurred on browser/platform 
We're running our test suite using a **selenium-chrome docker image** ([selenium/standalone-chrome-debug:3.4.0-einsteinium](https://hub.docker.com/r/selenium/standalone-chrome-debug/)), and tests are executed through the **wdio-cucumber-framework** (https://github.com/webdriverio/wdio-cucumber-framework)

**Comment by wvankuipers** [comment]
Hi @glenheide,

Thanks for pointing this out.
I will look into this in the near feature.
