### ISSUE TITLE
Tests for which there are no steps defined pass

### ISSUE THREAD

**Issue by FlippieCoetser** [webdriverio/cucumber-boilerplate#159]
# Issue description
Tests for which there are no steps defined pass

# Steps to reproduce
Using the following feature file
```
Feature: Local server test
    As a developer
    I want google site have the correct title

    Background:
        Given I open the url "http://www.google.com"
        And I pause for 500ms

    Scenario: Check Title
        Then I expect that the title is "Google"
```
and the following step file
```javascript
defineSupportCode(({ Given, Then}) => {
    Given(/^I open the (url|site) "([^"]*)?"$/, action.Open);
    Given(/^I pause for (\d+)ms$/, action.Pause);
    Then(/^I expect that the title is( not)* "([^"]*)?"$/, check.Title)
})
```
All three tests pass.
Now changing only the feature file to 

```
Feature: Local server test
    As a developer
    I want google site have the correct title

    Background:
        Given I open the url "http://www.google.com"
        And I pause for 500ms

    Scenario: Check Title
        When I expect that the title is "Google"
```
Note: Notice the `Then` has been changed to `When`

All three tests still pass.

# Expected behavior
A test for which there is no step defined should not pass

**Comment by christian-bromann** [comment]
I believe it doesn't really matter if you define your step definition as `when` or `then`. This is the nature of cucumber.js. Correct me if I am wrong @wvankuipers.
