### ISSUE TITLE
What IDE used for debug?

### ISSUE THREAD

**Issue by stamatovg** [webdriverio/cucumber-boilerplate#160]
# What IDE used for debug?
>  I mean is it possible to add breakpoint in steps and how? Thanks :)

**Comment by christian-bromann** [comment]
Please have a look at http://webdriver.io/guide/testrunner/debugging.html#Node-built-in-debugging-with-chrome-devtools.
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
