### ISSUE TITLE
Failed to run only the tests with specific tag(s)

### ISSUE THREAD

**Issue by learningCodes007** [webdriverio/cucumber-boilerplate#175]
# Issue description
> I want to execute only two scenarios from specs file - attribute.feature.
But unable to execute scenarios with specific tag(s)
# Steps to reproduce
>Open specs file - attribute.feature from features folder
 > Add tag 'execute' two below scenarios
e.g.
@execute
    Scenario: The attribute "role" of a element should not be "main"
        Then  I expect that the attribute "role" from element "#attributeComparison" is not "main"
  @execute
    Scenario: The (missing) CSS attribute "border" of a element should not be "0"
        Then  I expect that the css attribute "border" from element "#cssAttributeComparison" is not "0"

> Run test 
- yarn run wdio  --spec ./test/features/attribute.feature --cucumberOpts.tagExpression=@execute
OR
- yarn run wdio   --cucumberOpts.tagExpression=@execute

# Expected behavior
> Those two tagged scenarios should execute 

# Actual behavior
> No scenarios were executed.
- console : Number of specs: 29 : 0 passing

# Issue occurred on browser/platform 
> What platform did you experience this issue on? If you tested multiple browsers/platforms please add them, if you did not experience the issue on other tested browsers or platforms note it as well.

**Comment by amolebhojane** [comment]
@learningCodes007 even i am facing the same issue..  cannot able to execute specific scenario with tagname..   :(  even if i mentioned tag it is executing all the scenarios from file.. need help

**Comment by christian-bromann** [comment]
This is an issue with the wdio-cucumber-framework. We are trying to fix this for v5. Right now there is no immediate solution to this. Suggestions and PRs are always appreciated though.

**Comment by christian-bromann** [comment]
See also webdriverio/webdriverio#1247

**Comment by RobbieDixonSMS** [comment]
I resolved this issue by containing my argument in triple double quotes:

**npx wdio wdio.conf.js --cucumberOpts.tagExpression """@smoke or @sanity"""**

My source is here:

https://www.npmjs.com/package/@wdio/cucumber-framework?activeTab=readme
