### ISSUE TITLE
Scenario Outline not working

### ISSUE THREAD

**Issue by RoscoV3** [webdriverio/cucumber-boilerplate#18]
I started using your boiletplate recently and it's bee great so far.  

I was trying to use a Scenario Outline to cut down on cucumber test file bulk.  It was just passing the tests even when I set them to fail by using the wrong information in the table.

I thought cucumber had all this setup by default.

**Comment by wvankuipers** [comment]
The boilerplate is not using Cucumber but Yadda (which is a bit confusing given the name of the project)
Yadda uses a slightly different syntax for example data tables, you can find the [documentation here](https://acuminous.gitbooks.io/yadda-user-guide/content/en/feature-specs/example-tables.html)

**Comment by DenQ** [comment]
@wvankuipers , Yes, you guessed with name of project. :sarcasm:

**Comment by christian-bromann** [comment]
This became obsolete with recent update.

**Comment by kaasbaardje** [comment]
Hi. What does this mean? Is there still a support for scenario outlines or not?

**Comment by christian-bromann** [comment]
> Is there still a support for scenario outlines or not?

Scenario outlines are supported. This thread is outdated.

**Comment by kaasbaardje** [comment]
sry. but i tried it. i got a parser error and can't find an working example..

**Comment by wvankuipers** [comment]
Here is an example:

    Feature: Test buttons

    Scenario Outline: navigation button <Button>
        When  I click on the element "<Button>"
        Then  I expect that the path is "<Url>"

        Examples:
            | Button        | Url        |
            | nav a.home    | /          |
            | nav a.about   | /about/    |
            | nav a.product | /products/ |
            | nav a.contact | /contact/  |

Other examples & documentation can be found [here](https://github.com/cucumber/cucumber/wiki/Scenario-Outlines)

**Comment by worc** [comment]
that page no longer exists and the docs beyond that are pretty lacking.
