### ISSUE TITLE
Updating chrome to 64.0.3282.140 causes errors and breaks tests.  

### ISSUE THREAD

**Issue by prachipdesai** [webdriverio/cucumber-boilerplate#184]
# Issue description
> On updating chrome, the test cases did not run as expected.

# Steps to reproduce
> The test case feature is given below which is suppose to run on the latest version of chrome.

# Expected behavior
> The test case to run successfully. 

     Create and delete a one time transfer service request from Woodforest National Bank
       √ I open the site "/#/login"
       √ I wait on element "#username" for 30000ms to exist
       √ I wait on element "#password" for 30000ms to exist
       √ I set "retail_test@tradepmr.com" to the inputfield "#username"
       √ I set "qa777!!!" to the inputfield "#password"
       √ I click on the button "#submit-button"
       √ I wait on element ".user-info__name" to contain a text
       √ I open the site "/#/servicerequests/new/ach-initial"
 8 passing (22s)

Done in 25.37s.

# Actual behavior
>The test case freezes once the site is opened.

     Create and delete a one time transfer service request from Woodforest National Bank
       √ I open the site "/#/login"
       √ I wait on element "#username" for 30000ms to exist
       √ I wait on element "#password" for 30000ms to exist
       √ I set "blah" to the inputfield "#username"
       √ I set "blah" to the inputfield "#password"
       √ I click on the button "#submit-button"
       √ I wait on element ".user-info__name" to contain a text
       1) I open the site "/#/servicerequests/new/ach-initial"

1) Create and delete a one time transfer service request from Woodforest National Bank18 I open the site "/#/servicerequests/new/ach-initial":
function timed out after 20000 milliseconds
Error: function timed out after 20000 milliseconds at Timeout.

# Issue occurred on browser/platform 
> Google Chrome latest version 64.0.3282.140. 

```
Feature: test
 
 Background: 
    Given I open the site "/#/login"
    Then  I wait on element "#username" for 30000ms to exist 
    Then  I wait on element "#password" for 30000ms to exist 

 Scenario: Test scenario that crashes

    When  I set "blah" to the inputfield "#username" 
    When  I set "blah" to the inputfield "#password" 
    When  I click on the button "#submit-button"
    Then  I wait on element ".user-info__name" to contain a text 

    # causes test to freeze
    Given I open the site "/#/servicerequests/new/ach-initial"
```

**Comment by christian-bromann** [comment]
@prachipdesai not sure why this is an issue with the boilerplate. Maybe there is a bug with the latest Chrome version. The error definitely doesn't relate to the boilerplate.
