### ISSUE TITLE
stepdefinition is not defined

### ISSUE THREAD

**Issue by girishkumar517** [webdriverio/cucumber-boilerplate#185]
# Issue description
I am using webdriverio,my step definitions are not executing.Error is "Stepdefinitions are not defined"

# Steps to reproduce
> How can you reproduce the issue you are facing?

# Expected behavior
> What did you expect to happen?

# Actual behavior
> What did happen?

# Issue occurred on browser/platform 
> What platform did you experience this issue on? If you tested multiple browsers/platforms please add them, if you did not experience the issue on other tested browsers or platforms note it as well.

**Comment by christian-bromann** [comment]
@girishkumar517 sorry without any detailed description or a reproducible example there is no chance someone can help you. Please try in our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!
