### ISSUE TITLE
Screenshot is capturing desktop instead of browser window

### ISSUE THREAD

**Issue by Phenomen** [webdriverio/cucumber-boilerplate#187]
# Issue description
> Please provide a brief description of the problem you are experiencing

# Steps to reproduce
> 1. Make some test fail.
> 2. Check screenshot taken.

# Expected behavior
> Screenshot has only browser window of the failed test.

# Actual behavior
> Screenshot has the whole desktop screen.

# Issue occurred on browser/platform 
> Windows 10, Yarn 1.3.2, Node 9.5.0, Chrome 64.0.3282.140

**Comment by dpk1028** [comment]
Hi,

Can you please tell me if this example runs on the browser visually and not headless?

**Comment by christian-bromann** [comment]
Closing this. Without any description, logs or any reproducible example it's impossible to help here.
