### ISSUE TITLE
On Windows "npm run wdio" fails, but "yarn run wdio" succeeds

### ISSUE THREAD

**Issue by jpratt2** [webdriverio/cucumber-boilerplate#193]
# Issue description
> Please provide a brief description of the problem you are experiencing
I didn't install yarn and tried using NPM to install this boilerplate. On 2 different windows machines (Windows 8.1 and Windows 7), installation failed with the error:
 Error: missing script: wdio

Of course, using yarn had no issue. I just want to report this in case it helps you make it more compatible with an NPM installation.
# Steps to reproduce
https://github.com/webdriverio/cucumber-boilerplate
download, unzip, command line into the folder and type:

npm install
npm run local-webserver
npm run wdio

# Expected behavior
> What did you expect to happen?

# Actual behavior
> What did happen?

# Issue occurred on browser/platform 
> What platform did you experience this issue on? If you tested multiple browsers/platforms please add them, if you did not experience the issue on other tested browsers or platforms note it as well.

**Comment by christian-bromann** [comment]
@jpratt2 can you please provide more information on the issue? This literally tells me nothing :-/

**Comment by jpratt2** [comment]
Sure.  I cannot start the program by typing this:
npm run wdio

However, I can start the program by typing this:
yarn run wdio

Your documentation suggests that npm should work, but I am happy to use yarn if that is how it should work.

The steps I used to try to install this using yarn were exactly the same as using npm, except I replaced "yarn" with "npm".

**Comment by wvankuipers** [comment]
@jpratt2 Thanks for the video, that is realy helpfull 👍 

The command you used `npm run wdio` is not part of the boilerplate (it is just running `./node_modules/.bin/wdio`) the commands provided by the boilerplate are listed in the [package.json](https://github.com/webdriverio/cucumber-boilerplate/blob/master/package.json)

**Comment by gauravcap01** [comment]
Hi , 

I am getting same error on "npm run local-webserver".

**Error: missing script: local-webserver**
 
Logs:
1 verbose cli   'run',
1 verbose cli   'local-webserver'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose stack Error: missing script: local-webserver
