### ISSUE TITLE
Take a screenshot in BDD

### ISSUE THREAD

**Issue by VincentKLX** [webdriverio/cucumber-boilerplate#197]
Hello,

Can I take screenshot with a simple BDD command ?

Like : 
`Then I take a screenshot`

Thanks you !

**Comment by christian-bromann** [comment]
Yes, but it is not predefined for you, you need to extend the existing [step definitions](https://github.com/webdriverio/cucumber-boilerplate/blob/master/src/steps/then.js)

**Comment by christian-bromann** [comment]
Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
