### ISSUE TITLE
facing issue while using "and" keyword in cucumberOpts:tagExpression while running two scenarios..

### ISSUE THREAD

**Issue by janardanb** [webdriverio/cucumber-boilerplate#198]
# Issue description
> facing issue while using "and" keyword in cucumberOpts:tagExpression in wdio.conf.js file while running two scenarios..

# Steps to reproduce
> How can you reproduce the issue you are facing?

# Expected behavior
> two scenarios should run

# Actual behavior
> it is not working however it is working for or and not keyword..

# Issue occurred on browser/platform 
> What platform did you experience this issue on? If you tested multiple browsers/platforms please add them, if you did not experience the issue on other tested browsers or platforms note it as well.

**Comment by wvankuipers** [comment]
Please see #207
