### ISSUE TITLE
Under which exact circumstances are multiple browser instances created?

### ISSUE THREAD

**Issue by ThomasFett** [webdriverio/cucumber-boilerplate#2]
Not sure if this issue is only related to the boilerplate, or also to the webdriverIO multiremote mode:

When I have set options for my browser instances in my default `config.js`:

    ...,
    options: {
        browser1: {
            logLevel: 'silent'
        },
        browser2: {
            logLevel: 'silent'
        }
    },
    ...

but I want to execute a test with only one browser instance, I use the ENV_NODE variable and write a file `config.myCustomTest.js` containing:

    ...,
    capabilities: {
        browser1: {
            platform: "WINDOWS",
            browserName: "chrome"
            }
        }
    },
    ...

This leads to the execution of the tests with two browsers (where the capabilities of browser2 are undefined and change on every execution). It seems that the options, which are set in `config.js` are enough to trigger the execution in multiple browsers. It would be much nicer, if I could set my default for the options without having to overwrite them every time, if I need less browsers than I have options for, because I'm usually not changing the options from test to test and would love to set these values as default.

**Comment by christian-bromann** [comment]
this got obsolete with recent update
