### ISSUE TITLE
Incorrect order in checkUrl helper & missing this. in isExisting helper

### ISSUE THREAD

**Issue by wvankuipers** [webdriverio/cucumber-boilerplate#20]
Hello,

I found to issues in the test templates.

The first is a incorrect order of element in the `checkUrl` helper:
    
    result.value.should.equal(url, 'expected url to be "<result>"  but found "<expected>');

This should be:

    result.value.should.equal(url, 'expected url to be "<expected>"  but found "<result>');

The other issue is with the `isExisting` helper on line 6:

    browser.elements(selector, function (err, elements) {
    
The `this.` reference is missing:

    this.browser.elements(selector, function (err, elements) {

I created a pull request that will correct both issues.

**Comment by christian-bromann** [comment]
Let's move convo to #21
