### ISSUE TITLE
running multiple Cucumber tags are not working

### ISSUE THREAD

**Issue by AbinashB** [webdriverio/cucumber-boilerplate#207]
# Issue description
>multiple tags are not running using cucumber tag option.
working for the single tag only
# Steps to reproduce
>  $ yarn run wdio -- --cucumberOpts.tagExpression=@Sanity,@Regression 

# Expected behavior
> should run Sanity and Regression

# Actual behavior
> Not running anything

# Issue occurred on browser/platform 
> MAC & Chrome

>Note: Single tag works fine. example- yarn run wdio -- --cucumberOpts.tagExpression=@Sanity works fine.

**Comment by AbinashB** [comment]
@wvankuipers any idea?

**Comment by HvandenBerg** [comment]
@wvankuipers I've seen the same issue and your new tag style works, it's not just the word or but also make sure to include the ' before and after the tags you want to run.

**Comment by wvankuipers** [comment]
@HvandenBerg Thanks for the feedback, will update the readme to reflect this.

**Comment by wvankuipers** [comment]
You could use the [Gitter](https://gitter.im/webdriverio/webdriverio) channel for WebdriverIo

**Comment by RobbieDixonSMS** [comment]
I resolved this issue by containing my argument in triple double quotes:

**npx wdio wdio.conf.js --cucumberOpts.tagExpression """@smoke or @sanity"""**

My source is here:

https://www.npmjs.com/package/@wdio/cucumber-framework?activeTab=readme
