### ISSUE TITLE
Pending tests are being executed anyway

### ISSUE THREAD

**Issue by LaiaPR** [webdriverio/cucumber-boilerplate#209]
# Issue description
Scenarios tagged as Pending are being executed anyway.

# Steps to reproduce
Got some flaky scenarios tagged as `@Pending`

In my cucumberOpts config, I got:
`tagExpression: 'not @Pending'`

Also tested running tests with:
`yarn run wdio --cucumberOpts.tagExpression='not @Pending'`

# Expected behavior
"Pending" scenarios not being executed (and not marked as failing)

# Actual behavior
"Pending" scenarios are being executed and failing 😞 

# Issue occurred on browser/platform 
Running tests with Chrome.  In my package.json I got:
`"wdio-cucumber-framework": "~2.1.0"`

**Comment by asidarovich** [comment]
+1
Issue still persists

**Comment by christian-bromann** [comment]
We updated the boilerplate, please check if you still experience this issue. Thanks!
