### ISSUE TITLE
Remove { defineSupportCode } from steps

### ISSUE THREAD

**Issue by juw177** [webdriverio/cucumber-boilerplate#211]
There is no need to wrap the steps with defineSupportCode.

import { Given } from 'cucumber';

Is sufficient.

**Comment by christian-bromann** [comment]
@juw177 feel free to provide a PR

**Comment by lrocheWB** [comment]
https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md

Replace by:
```
var {Given} = require('cucumber');
Given(/^a step$/, function() {});
```

**Comment by christian-bromann** [comment]
Yes

**Comment by lrocheWB** [comment]
You can close this issue @christian-bromann :)

**Comment by christian-bromann** [comment]
Thanks @lrocheWB
