### ISSUE TITLE
Cucumber WDIO Boilerplate has dependancy on http://webdriverjs.christian-bromann.com/

### ISSUE THREAD

**Issue by computamike** [webdriverio/cucumber-boilerplate#226]
# Issue description
While running the unit tests (yarn test) on cucumber-boilerplate, there are tests that call this server.  These tests are used as part of the pull request process and if this external site were to go offline, this would prevent pull requests from operating.  

# Steps to reproduce
yarn test

# Expected behavior
Wasn't expecting a dependency on an external website, considering that the test project does have a test website that is served

# Actual behavior
Tests (Sample Snippets test) has a dependency on an external website.

# Issue occurred on browser/platform 
Tested on Macbook

**Comment by christian-bromann** [comment]
@computamike we decided to use this package for simplicity reasons. This page will not go offline. Feel free to provide a PR that removes the dependency.

**Comment by christian-bromann** [comment]
Replaced urls with a page hosted on S3
