### ISSUE TITLE
Corporate proxy issue blocking the chromedriver 

### ISSUE THREAD

**Issue by id4automation** [webdriverio/cucumber-boilerplate#229]
# Issue description
I am trying to set wdio framework in my windows os. I did a clean set  up of the cucumber-boilerplate project as mentioned. But upon executing yarn run wdio , I am getting  the below error message.

> A service failed in the 'onPrepare' hook
> Error: Could not download https://chromedriver.storage.googleapis.com/2.40/chromedriver_win32.zip: Error: tunneling socket could not be established, statusCode=403
>     at Request.<anonymous> (C:\dev\integration\node_modules\selenium-standalone\lib\install.js:386:12)
>     at Object.onceWrapper (events.js:315:30)
>     at emitOne (events.js:116:13)
>     at Request.emit (events.js:211:7)
>     at Request.onRequestError (C:\dev\integration\node_modules\request\request.js:877:8)
>     at emitOne (events.js:116:13)
>     at ClientRequest.emit (events.js:211:7)
>     at ClientRequest.onConnect (C:\dev\integration\node_modules\tunnel-agent\index.js:168:23)
>     at Object.onceWrapper (events.js:319:30)
>     at emitThree (events.js:136:13)

I also received a html output which states 

>  <FONT face="Helvetica">
>   A communication error occurred: "Connection refused"
>   </FONT>
>   </TD></TR>
>   <TR><TD>
>   <FONT face="Helvetica">
>   The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
>   </FONT>

Could you provide the workaround inputs to by pass the corporate proxy please.

**Comment by id4automation** [comment]
Contd...

I also tried including the corporate proxy inside the wdio.conf.js file

 capabilities: [{
        // maxInstances can get overwritten per capability. So if you have an
        // in-house Selenium grid with only 5 firefox instance available you can
        // make sure that not more than 5 instance gets started at a time.
        maxInstances: 5,
        //
        browserName: 'chrome',
		proxy: {
                proxyType: 'MANUAL'
                , httpProxy: 'proxy-url-without-http-infront:8000'
                , sslProxy: 'proxy-url-without-http-infront:8000'
            }
    }],

Still facing the same issue.

**Comment by abianche** [comment]
I faced a similar issue some time ago, with our corporate proxy. Setting the proxies in the chrome capabilities part did not work. What worked was to set the proxy to Selenium, in the wdio config:

`seleniumInstallArgs: {
    proxy: "http://your-corporate-proxy:port"
}`
See also http://webdriver.io/guide/services/selenium-standalone.html#seleniumInstallArgs.
Hope that helps!

**Comment by christian-bromann** [comment]
We updated the boilerplate, please check if you still experience this issue. Thanks!
