### ISSUE TITLE
Improve documentation on how to keep own cucumber tests in sync with cucumber-boilerplate

### ISSUE THREAD

**Issue by cbou** [webdriverio/cucumber-boilerplate#238]
The README says to remove the .git folder.
I wonder how to apply changes on the cucumber-boilerplate to my new repository (or the existing repository of my product).

**Comment by wvankuipers** [comment]
Hi Charles,

The best way to do this is to add the boilerplate to an existing project (that is managed by GIT or any other version control system.

the `.git` folder inside the cucumber-boilerplate project refers to this repository, and you probably don't want your changes to be published here ;)

**Comment by cbou** [comment]
Thanks @wvankuipers !

What you are saying makes totally sense. My issue is that let's say I clone `cucumber-boilerplate` the Mar 7, 2018. I have no way to get the commits and changes which came after the Mar 7, 2018. My Boilerplate is stick with old dependencies forever.

I don't know if there is a way to get the commits and changes after you remove the .git folder.

Maybe it could be possible to build this boilerplate like a single plugin so that it has only a single dependency....

**Comment by christian-bromann** [comment]
@cbou this boilerplate is just a project that you can integrate into your project to get started with testing. It is not meant to auto update itself. Once you integrated it you are responsible for maintaining your tests. You can always look at what hase changed here and adapt those changes into your project too.
