### ISSUE TITLE
Unable to get screen shots to be taken on error

### ISSUE THREAD

**Issue by dtzar** [webdriverio/cucumber-boilerplate#243]
# Issue description
I cannot get the screenshots to take on error.

# Steps to reproduce
Have a test which fails using latest version of Chrome browser (full browser, not headless).   See [this gist](https://gist.github.com/dtzar/e2f18c716bf9bff5d8452f7c24068c97#file-wdio-config) for my actual configuration.

```
    // Saves a screenshot to a given path if a command fails.
    screenshotPath: "./errorShots/",
    // take screenshot on reject
    screenshotOnReject: true,
```
# Expected behavior
When a step fails a screenshot of the open browser would be taken.

# Actual behavior
All the tests executed as expected including producing a junit report file, but no screenshots were produced.

# Issue occurred on browser/platform 
Running this on the latest version of Windows 10, JDK 8, latest version of cucumber tool framework.  Can see my [package.json here](https://gist.github.com/dtzar/e2f18c716bf9bff5d8452f7c24068c97#file-package-json). Started with your default package.json and started updating packages to see if this would change anything and it did not.

**Comment by christian-bromann** [comment]
We updated the boilerplate, please check if you still experience this issue. Thanks!
