### ISSUE TITLE
Dictionary definitions are ignored

### ISSUE THREAD

**Issue by cressie176** [webdriverio/cucumber-boilerplate#25]
Dictionary definitions are being ignored because the library is not being initialised with the dictionary on https://github.com/webdriverio/cucumber-boilerplate/blob/master/test/support/step-definitions.js#L10-L11

If you change this to 
```
var dictionary = new Yadda.Dictionary();
var library = language.library(dictionary);
```
The definitions start getting picked up.

**Comment by christian-bromann** [comment]
superseded by #29
