### ISSUE TITLE
Detecting element by text in `waitForVisible` function.

### ISSUE THREAD

**Issue by krzywiecki** [webdriverio/cucumber-boilerplate#253]
# Issue description
Detecting element by text in `waitForVisible` function.

It's just a question. I'm wondering if it's possible somehow to detect element by text in `I expect that element "<string>" becomes visible`. I mean, I would like to check if an element with particular text become visible on my website but I don't want to specify any other selector as this seems to be quite fragile for changes. So for example in my case, the step would look like:
`I expect that element "=With text" becomes visible`. 

I'll try to figure it out on my own and raise PR but in meantime, any suggestions are very welcome :v:

**Comment by christian-bromann** [comment]
We updated the boilerplate, please check if you still experience this issue. Thanks!
