### ISSUE TITLE
Webserver not starting

### ISSUE THREAD

**Issue by stephandekker** [webdriverio/cucumber-boilerplate#258]
# Issue description

"yarn run local-webserver" seems to exit immediately.

# Steps to reproduce

1) Clone git repo on MacBook Pro
2) yarn install
3) yarn run local-webserver

# Expected behavior
Being able to browse to localhost:8080

# Actual behavior

Browsing to localhost:8080 gives:  Connection Refused

Console Output:

yarn run v1.16.0
$ forever start -s ./node_modules/.bin/http-server ./demo-app -s
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: ./node_modules/.bin/http-server
✨  Done in 0.60s.

# Issue occurred on browser/platform 
Macbook Pro
Mojava 10.14.5, 16GB RAM, Intel I7

**Comment by christian-bromann** [comment]
Please check latest master version. It should be fixed now.
