### ISSUE TITLE
Currently this boilerplate is not providing any test results? 

### ISSUE THREAD

**Issue by psubrambe** [webdriverio/cucumber-boilerplate#270]
# Issue description
BoilerPlate doesn't have the Reporting Functinolity

# Steps to reproduce
Run the boilerPlate any testcases
Doesn't produce any test output

# Expected behavior
Need to produce final results
# Actual behavior
Test results are not produced

**Comment by christian-bromann** [comment]
In the config it defines a spec reporter: https://github.com/webdriverio/cucumber-boilerplate/blob/master/wdio.conf.js#L119 so you should see something in stdout. If you want to use other reporters you can also do that.

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
