### ISSUE TITLE
Is there is functionality or snippets available for capturing the SessionID from the Source code ?

### ISSUE THREAD

**Issue by psubrambe** [webdriverio/cucumber-boilerplate#271]
# Issue description
Need a SNIPPET to capture a session id of test

# Expected behavior
Need a Snippet to capture a session id

**Comment by christian-bromann** [comment]
See https://webdriver.io/docs/browserobject.html

Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
