### ISSUE TITLE
I made a library out of this and added more features.

### ISSUE THREAD

**Issue by SantoJambit** [webdriverio/cucumber-boilerplate#293]
# Issue description
Hello,

I found this boilerplate a while ago during my day job and have since improved on it both in my private time and my work time. Recently I got permission from [my employer](https://jambit.com/) to publish this as open-source project and as a public NPM package.

Check out the [readme](https://github.com/jambit/wdio-cucumber-selected-steps/blob/master/README.md) of the project to see how this differs from the boilerplate.

In short:
- Cleaned up sentences
- Easy to import via npm dependency
- CSS / XPath selectors are not written in feature files.
- Type conversion for values extracted by the regular expressions. (like int, bool, float, element, elements, selector).

The library: https://github.com/jambit/wdio-cucumber-selected-steps
The demo project: https://github.com/jambit/wdio-cucumber-selected-steps-demo

I would love some feedback, or even better some pull requests to further improve this. Also, it would be awesome if you could mention this in the readme of this project or the webdriver.io page (blog or otherwise).

Cheers

**Comment by christian-bromann** [comment]
@SantoJambit sorry for getting back to this so late. Fantastic work! Please make a PR to this repositories readme and add a link to your project.

Thank you!
