### ISSUE TITLE
How to run a test in isolation?

### ISSUE THREAD

**Issue by obsidianart** [webdriverio/cucumber-boilerplate#3]
Is there any way to run a test in isolation while developing? I see "Pending" but not "Isolate".
If is not a feature yet, is there a better way then looping on the file looking for the isolation tag and run if found, otherwise run all?

**Comment by christian-bromann** [comment]
There is unfortunately no counterpart for `@Pending`. Looping over all files might be the best choice here. Can you share your approach? So I can add that to the boilerplate code.

**Comment by obsidianart** [comment]
Created a pull request to add @Isolate, have a look

**Comment by christian-bromann** [comment]
Thanks. Let's continue our convo at #4
