### ISSUE TITLE
How to do the Parameterization in feature file?

### ISSUE THREAD

**Issue by Pavankumar95153** [webdriverio/cucumber-boilerplate#302]
how to do the parameterization to test with different data in cucumber wdio.

**Comment by osmolyar** [comment]
@Pavankumar95153  questions are more appropriate for the gitter webdriverio channel https://gitter.im/webdriverio/webdriverio.    This is basic cucumber functionality.  There is a tutorial for using cucumber with webdriverio here https://testautomationu.applitools.com/cucumber-javascript-tutorial/
