### ISSUE TITLE
Bad link in README

### ISSUE THREAD

**Issue by ctgraham** [webdriverio/cucumber-boilerplate#342]
# Issue description
> Gherkin syntax link has moved

# Steps to reproduce
> Click https://cucumber.io/docs/reference at https://github.com/webdriverio/cucumber-boilerplate/blame/bbe82ef73b221e8c897a1bc0ff444f36b44b86c8/README.md#L52

# Expected behavior
> Gherkin docs (https://cucumber.io/docs/gherkin/)

# Actual behavior
> 404

# Issue occurred on browser/platform 
> n/a

**Comment by christian-bromann** [comment]
PR was merged. Thanks!
