### ISSUE TITLE
Travis builds are failing for MR's

### ISSUE THREAD

**Issue by tejasv02** [webdriverio/cucumber-boilerplate#356]
# Issue description
> npm run test works fine on my machine but it's failing test on Merge Requests (MR).

# Steps to reproduce
> Create a new MR on https://github.com/webdriverio/cucumber-boilerplate and wait for tests to execute

# Expected behavior
> Test must pass

# Issue occurred on browser/platform 
> Node version used for test execution must reflect the node version used in nvmrc, possible nvm use must be executed before test.

**Comment by christian-bromann** [comment]
I update the dependencies. Please rebase your MR on top of current master and your build should pass.

**Comment by tejasv02** [comment]
Thanks
