### ISSUE TITLE
Installing cucumber-boilerplate as an NPM package?

### ISSUE THREAD

**Issue by rorymckinley** [webdriverio/cucumber-boilerplate#39]
I am afraid I am a javascript/NPM noob, but is there any reason why cucumber-boilerplate is not available as an NPM module? I have a client who is considering using cucumber-boilerplate and it would make management easier if we could install it via NPM.

If the reason is simply that it is just not a priority (as opposed to technical reasons) I am happy to do the legwork, if somebody can point me in the right direction in terms of getting started.

**Comment by christian-bromann** [comment]
Hi @rorymckinley 
this is not an NPM module and more a boilerplate you can fork and use it as starting point.

Cheers
