### ISSUE TITLE
Making config data available to step helpers/snippets

### ISSUE THREAD

**Issue by rorymckinley** [webdriverio/cucumber-boilerplate#41]
At the moment, based on reading the code, the config object that is created in init.js is not available to steps or their helpers/snippets.

I have some complicated orchestration which requires access to the config data, and I am wondering which would be the recommended approach?

1) Make the config object globally available
or
2) Require configure.js wherever it is required.

**Comment by christian-bromann** [comment]
This became obsolete with recent update.
