### ISSUE TITLE
Docs say to execute yarn run local-webserver but there is none

### ISSUE THREAD

**Issue by pgr1973** [webdriverio/cucumber-boilerplate#418]
# Issue description
The README.md tells us to 'yarn run local-webserver', but there is none installed (and probably also non configured):
`$ yarn run local-webserver`
`yarn run v1.22.4`
`error Command "local-webserver" not found.`

# Steps to reproduce
`yarn install`
`yarn run local-webserver`

# Expected behavior
the local webserver to start so the tests can run

# Actual behavior
`error Command "local-webserver" not found.`

# Issue occurred on browser/platform 
Win10, Gitlab with docker-image 'node:lts-alpine'

**Comment by christian-bromann** [comment]
@pgr1973 this seems to be an outdated documentation bit. It seems that tests are currently being run by calling `npm test` and a local webserver isn't needed anymore as we define a static service in the [wdio config](https://github.com/webdriverio/cucumber-boilerplate/blob/master/wdio.BUILD.conf.js#L28-L36). Would you like to help us update the docs?

**Comment by pgr1973** [comment]
@christian-bromann: > Would you like to help us update the docs?

Sure. But I don't know how.

**Comment by christian-bromann** [comment]
> Sure. But I don't know how.

You can fork the project and make changes to the README.md. There are plenty of tutorials on how to do that on the internet. This could be a great OSS contribution!

**Comment by mir-nawaz** [comment]
This is fixed in [PR 419](https://github.com/webdriverio/cucumber-boilerplate/pull/419)

**Comment by christian-bromann** [comment]
Closing then, thanks @mir-nawaz
