### ISSUE TITLE
How to end session and start again in scenario?

### ISSUE THREAD

**Issue by OpakAlex** [webdriverio/cucumber-boilerplate#42]
I have some problem, I have ane Feature with all login actions. 
First Scenario checks correct login, second incorrect, but problem, if first scenario pass, i still loggined. How to clear session?

**Comment by jjanssen** [comment]
Within our project we have the same situation. 

If we have a feature which requires a clean state on every scenario, we add a background to it. Within the scenario background we always clear our session cookies to make sure either a visitor has an empty shopping basket or isn't logged in.

You could add the something like this, which contains the two default boilerplate rules:
```
Given I open the site "/"
When I delete the cookie "mysession_cookie"
Given I open the site "/restricted_area/"
```

This creates a little overhead, mainly because the deleting a cookie requires the context of your page to test.

You could eventually add your own rule to the boilerplate to open your URL by default, delete the cookie and go to your restricted area URL. In our case we have added custom rule to our project like, for eg `Given I have destroyed my session`.

**Comment by OpakAlex** [comment]
@jjanssen thanks man, not so help, but it depends on app.
But i detected anther so strange issue, i want post it here, maybe you can help me.
So, we have feature:
```cucumber
Feature: Edit Profile

  # Background:
    # Given a regular logged-in user

  Scenario: View the edit profile page
    Given a regular logged-in user
    Given I am on the edit profile page
    Then I should see my email, first name and last name

  @Only  
  Scenario: Edit my profile
    Given a regular logged-in user
    Given I am on the edit profile page
    When I change my first name to "firstNameDemo" and last name to "lastNameAccount"
    Then I should see my new name "Demo1 Account1" in the navigation bar
```

First scenario check some form fields, easy:
```js
var page = require('../pageObjects/profilePage');
module.exports = function (done) {
    this.browser
    .getValue(page.email).then((text) => {
      text.should.equal("demo@intuo.io");
    })
    .getValue(page.firstName).then((text) => {
      text.should.equal("Demo");
    })
    .getValue(page.lastName).then((text) => {
      text.should.equal("Account");
    })
    .call(done);
};
```
This test always pass, look into next one:
```js
var page = require('../pageObjects/profilePage');

module.exports = function (firstName, lastName, done) {
    this.browser
        .waitForExist(page.firstName, 100000, null)
        // .element('.int-user-first-name').then(el => {
        //   el.value = firstName;
        //   console.log(el);
        // })
        .click(page.save)
        .call(done)
};
```
In second one i always have error like: 
  1) Edit Profile Edit my profile When I change my first name to "firstNameDemo" and last name to "lastNameAccount":
     Uncaught RuntimeError: no such element
      at elements(".int-user-first-name") - isExisting.js:43:17
      at isExisting(".int-user-first-name") - waitForExist.js:31:21

Set value can not works with same.. In screenshot a see fields.
```
What is wrong?

**Comment by OpakAlex** [comment]
@jjanssen one more, in this tests i always has 
`Uncaught Error: Promise was fulfilled but got rejected with the following reason: Error: no such window: target window already closedfrom unknown error: web view not found`

**Comment by OpakAlex** [comment]
I need one good working solution without magic....like this

**Comment by OpakAlex** [comment]
Looks like random error:
```
var page = require('../pageObjects/profilePage');

module.exports = function (firstName, lastName, done) {
    this.browser
        .setValue(page.firstName, firstName)
        .setValue(page.lastName, lastName)
        .click(page.save)
        .call(done)
};
```

```
λ ~/projects/intuo/gherkin-specs/features/ oa-cucumbers* ./test/run.js


  Edit Profile
    Edit my profile
      ✓ Given a regular logged-in user (5978ms)
      ✓ Given I am on the edit profile page (3622ms)
NoSuchElement: An element could not be located on the page using the given search parameters. 
    at elements("#user_last_name") - setValue.js:42:17
    at elementIdValue("4", "firstNameDemo") - setValue.js:53:7 
      1) When I change my first name to "firstNameDemo" and last name to "lastNameAccount"
      - Then I should see my new name "Demo1 Account1" in the navigation bar


  2 passing (18s)
  1 pending
  1 failing

  1) Edit Profile Edit my profile When I change my first name to "firstNameDemo" and last name to "lastNameAccount":
     Uncaught NoSuchElement: An element could not be located on the page using the given search parameters.
      at elementIdValue("4", "firstNameDemo") - setValue.js:53:7



λ ~/projects/intuo/gherkin-specs/features/ ./test/run.js


  Edit Profile
    Edit my profile
      ✓ Given a regular logged-in user (5485ms)
      ✓ Given I am on the edit profile page (3909ms)
      1) When I change my first name to "firstNameDemo" and last name to "lastNameAccount"
      - Then I should see my new name "Demo1 Account1" in the navigation bar


  2 passing (18s)
  1 pending
  1 failing

  1) Edit Profile Edit my profile When I change my first name to "firstNameDemo" and last name to "lastNameAccount":
     Uncaught RuntimeError: no such element
      at elementIdValue("5", "lastNameAccount") - setValue.js:53:7
```
@jjanssen i need you help. it's make me crazy, i am so near to remove all tests and never use this solution.

**Comment by OpakAlex** [comment]
And see previos step whic passed!

```
module.exports = function (done) {
    var url = this.baseUrl + '/profile/edit';
    this.browser
        .url(url)
        .pause(1000)
        .saveScreenshot("tmp1")
        .waitForVisible(".int-user-first-name", 6000, null)
        .waitForVisible(".int-user-last-name", 6000, null)
        .call(done);
};
```
`.int-user-first-name` -> `page.firstName` !!!!!!!

How it's can be? Prev step find element, but current step no? But i see it on screenshot!

**Comment by OpakAlex** [comment]
fixed by update selenium and webdriver :)
