### ISSUE TITLE
Multi mode for features

### ISSUE THREAD

**Issue by DenQ** [webdriverio/cucumber-boilerplate#43]
Hi. Your project very like me.
But, i wish to run my features in multi mode(parallel).
I saw  in README your have planned -  "Easy to run tests in parallel (coming soon)"  - it is very needed feature :+1:

I think it can be like it is code for example
```
@Multi
Feature: Some feature
```
or
```
@Multi
Scenario: Some scenario

```

**Comment by wvankuipers** [comment]
This is now implemented 👍 

You don't have to add the @Multi tag, teh configuration is in the main configuration file

**Comment by christian-bromann** [comment]
Closing
