### ISSUE TITLE
Add tag configuration

### ISSUE THREAD

**Issue by joao-arvins** [webdriverio/cucumber-boilerplate#45]
Hi.
Does this solution allows adding a "tags" configuration parameter so that we can specify the test to run? (e.g run only the test with the @example annotation).

I'm trying to find it but so far no luck...

**Comment by benweizhu** [comment]
Same question.

**Comment by wvankuipers** [comment]
Please check the documentation for the current implementation [here](https://github.com/webdriverio/cucumber-boilerplate#using-tags)

**Comment by christian-bromann** [comment]
This became obsolete with the recent update.
