### ISSUE TITLE
Is it possible so that the browser closes after each test

### ISSUE THREAD

**Issue by cheapaschips** [webdriverio/cucumber-boilerplate#46]
I just want to say great work on this frame work, from a non coder here learning JS it's an amazing piece of work!

I just have 2 questions though..

1. Is there anyway to ensure the browser quits after each test has complete?
2. Also is there a way that the selenium standalone server could start up prior to a test commencing?

Thanks in advance!

**Comment by christian-bromann** [comment]
> Is there anyway to ensure the browser quits after each test has complete?

I think this should work with this boilerplate out of a hook

> Also is there a way that the selenium standalone server could start up prior to a test commencing?

No with this boilerplate. I would recommend to move forward to use WebdriverIOs wdio test runner together with cucumberjs. All information can be found on http://webdriver.io
