### ISSUE TITLE
Error while executing the framework in Node version 16.3

### ISSUE THREAD

**Issue by jayakrishnanba** [webdriverio/cucumber-boilerplate#479]
Issue:
> wdio run wdio.conf.ts

Assertion failed: (thread_id_key != 0x7777), function find_thread_id_key, file ../src/coroutine.cc, line 134.
zsh: abort      npm run wdio

Description
I am unable to run the framework using node version 16.3. I have to downgrade to 15.14 to run it. Is the framework supporting 16.3

**Comment by christian-bromann** [comment]
We don't support synchronous command execution with Node.JS v16 anymore. Please read more about this here: https://webdriver.io/blog/2021/07/28/sync-api-deprecation
