### ISSUE TITLE
Not proper error message for duplicate step definition

### ISSUE THREAD

**Issue by vinodkpasi** [webdriverio/cucumber-boilerplate#484]
# Issue description
> I am using WebDriver version 7 with latest wdio/cucumber. When there is duplication step definition there is no proper error message for duplicate step definition.

# Steps to reproduce
> Implement duplicate step definition

# Expected behavior
> There should be proper error message like "Duplicate step definition found for step xyz"

# Actual behavior
> Process exited with code 1

# Issue occurred on browser/platform 
> Windows platform with chrome browser

**Comment by christian-bromann** [comment]
The Cucumber integration automatically detects duplicate steps and throws errors like this:

```ts
Multiple step definitions match:
  /^I open the (url|site) "([^"]*)?"$/ - file:/Users/christianbromann/Sites/WebdriverIO/cucumber-boilerplate/src/steps/given.ts:22
  /^I open the (url|site) "([^"]*)?"$/ - file:/Users/christianbromann/Sites/WebdriverIO/cucumber-boilerplate/src/steps/given.ts:23
```

Make sure you don't have the option set that would suppress this error.
