### ISSUE TITLE
Feature tests for demo-app failing

### ISSUE THREAD

**Issue by PavanMudigondaTR** [webdriverio/cucumber-boilerplate#489]
# Issue description
> Please provide a brief description of the problem you are experiencing
All features for Demo-app are failing. Just like https://github.com/webdriverio/cucumber-boilerplate/runs/5181495798?check_suite_focus=true

# Steps to reproduce
> How can you reproduce the issue you are facing?

Just like one of your workflow failure (link below)
https://github.com/webdriverio/cucumber-boilerplate/runs/5181495798?check_suite_focus=true

# Expected behavior
> What did you expect to happen?
Hoping tests to pass

# Actual behavior
> What did happen?
Failing tests
https://github.com/webdriverio/cucumber-boilerplate/runs/5181495798?check_suite_focus=true

# Issue occurred on browser/platform 
> What platform did you experience this issue on? If you tested multiple browsers/platforms please add them, if you did not experience the issue on other tested browsers or platforms note it as well.

Github Actions workflow using ubuntu and local on Mac. 

<img width="616" alt="image" src="https://user-images.githubusercontent.com/86745613/166297499-35e5feca-1cb7-417c-a8b1-004662d4d5e0.png">

**Comment by christian-bromann** [comment]
@PavanMudigondaTR have you tried to run them locally? I assume that there is a driver/browser version mismatch. You want to help us to fix the issue?

**Comment by christian-bromann** [comment]
Pushed a fix, tests are now passing in CI again.

**Comment by PavanMudigondaTR** [comment]
Thanks will try again

**Comment by PavanMudigondaTR** [comment]
> @PavanMudigondaTR have you tried to run them locally? I assume that there is a driver/browser version mismatch. You want to help us to fix the issue?

working fine now. thanks alot.
