### ISSUE TITLE
ChromeDriver installation failed Error: Error with http(s) request: Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by apreg** [webdriverio/cucumber-boilerplate#495]
# Issue description
> "ChromeDriver installation failed Error: Error with http(s) request: Error: self signed certificate in certificate chain" appears after issuing yarn install on Windows 10.
>  "error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style" after yarn run test
> "TypeError: Cannot read properties of undefined (reading 'extend')" after yarn run test

# Steps to reproduce
> First, issue `yarn install `then `yarn run test `on Windows from command line  or git bash

# Expected behavior
> No errors

# Actual behavior
> Errors

# Issue occurred on browser/platform 
> Windows 10
> webdriver.io git hash: d2adf44

# Solution
> In `node_modules\chromedriver\install.js` there is a code part that checks if `process.env.npm_config_ca` is defined and tries to use its content for building up the connection. In my case the value of process.env.npm_config_ca was an empty string so I had to make it null with `npm config ca null` and then set the cafile configuration property with this command: `npm config cafile <path to your pem file>`
> As for the linebreaks I had to edit .eslintrc.yaml in the workspace root and add these lines: 
```rules:
  linebreak-style: 
    - 'error'
    - 'windows'
```
> For the TypeError to disappear I had to edit jest.config.js in the workspace root and change 
` moduleDirectories: [
        'node_modules',
        '.',
    ],` to 
    ` moduleDirectories: [
        'node_modules',
        __dirname,
    ],`

**Comment by christian-bromann** [comment]
There seems to be an issue related to downloading Chromedriver. We are tracking the error here: https://github.com/webdriverio-community/wdio-chromedriver-service/issues/82
