### ISSUE TITLE
Tests fail with unsupported version of Chrome

### ISSUE THREAD

**Issue by psstoyanov** [webdriverio/cucumber-boilerplate#497]
# Issue description
Cloning the repo and attempting to run the tests, results in a failure

# Steps to reproduce
Clone the repository. Run `npm install .` && `npm run test`

# Expected behavior
All tests to pass

# Actual behavior
Throws errors for `chrome` tests. Extract from `./logs/wdio-0-0.log`:
```
2022-11-12T11:34:52.651Z DEBUG webdriver: request failed due to response error: session not created
2022-11-12T11:34:52.651Z ERROR webdriver: Request failed with status 500 due to session not created: session not created: This version of ChromeDriver only supports Chrome version 104
Current browser version is 107.0.5304.110 with binary path /usr/sbin/chromium
```

# Issue occurred on browser/platform 
- Chromium: `107.0.5304.110`

Would try with Firefox as well but this requires adjusting the [buildConfig services](https://github.com/webdriverio/cucumber-boilerplate/blob/0981585107e353e763cae2b4c87e595f4fc73956/wdio.BUILD.conf.ts#L24) and adding `firefox-profile-service` afaiu

**Comment by christian-bromann** [comment]
> This version of ChromeDriver only supports Chrome version 104

Seems like you are having the wrong `chromedriver` NPM package installed. Make sure you install the version that matches your Chrome (so `v107`), via:

```sh
npm install chromedriver@107
```
