### ISSUE TITLE
v7 link in README.md is not working

### ISSUE THREAD

**Issue by mikesalvia** [webdriverio/cucumber-boilerplate#513]
# Issue description
v7 link in README.md is not working

# Steps to reproduce
Click v7 in README.md on GitHub

# Expected behavior
v7 link should open new page.

# Actual behavior
404 is encountered

# Issue occurred on browser/platform 
Windows 10 in Chrome

**Comment by christian-bromann** [comment]
> v7 link in README.md is not working

Which v7 link?

**Comment by mikesalvia** [comment]
![image](https://user-images.githubusercontent.com/6209204/216678687-1ad6646c-537c-4359-9c17-60dc31aa5a6e.jpeg)

**Comment by mikesalvia** [comment]
We may want a v7 branch to track like in webdriverio and services.

**Comment by christian-bromann** [comment]
Thanks, I pushed a `v7` branch and updated the docs.
