### ISSUE TITLE
Cannot run features using tags 

### ISSUE THREAD

**Issue by claudiuionita** [webdriverio/cucumber-boilerplate#58]
> I've added some tags to my feature files and but they seem to be ignored by the CLI

> Steps: add a @tag to a feature file and then run it (wdio --tags=@auth) using the CLI 

> Expected:  I expect that the feature file containing @tag to run

> Actual: Browser opened, url did not load, it looked like @pending tags are running

> Windows 10 / Chrome

**Comment by wvankuipers** [comment]
@claudiuionita I can't reproduce this issue. Could you provide a sample feature file & the exact command you are using?
