### ISSUE TITLE
Naming conflict in custom given / when steps

### ISSUE THREAD

**Issue by jjanssen** [webdriverio/cucumber-boilerplate#62]
# Issue description
When having the same name within a `Given`  or `When` step the corresponding step no longer gets executed and the end result will be pending.

# Steps to reproduce
Create a custom step with the same name for `Given` and `When`.

Within `given.js`:
```
this.Given(
    /^foobar$/,
    (done) => { done(); }
);
```

Within `when.js`:
```
this.When(
    /^foobar$/,
    (done) => { done(); }
);
```

# Expected behavior
I expect the custom rule the get executed. Like:
```
[chrome #0-0]   My scenario
[chrome #0-0]       ✓ I open the site "/"
[chrome #0-0]       ✓ foobar
[chrome #0-0] 2 passing
```

# Actual behavior
The custom rule returns pending and does not get executed. Like:
```
[chrome #0-0]   My scenario
[chrome #0-0]       ✓ I open the site "/"
[chrome #0-0]       - foobar
[chrome #0-0] 1 passing
[chrome #0-0] 1 pending
```

# Issue occurred on browser/platform 
- NodeJS v5.6.0
- The latest master branch with the changes from #60 
- Chrome

**Comment by wvankuipers** [comment]
This seems to be an issue with Cucumber itself, all the rules from Then/When/Given are grouped and then executed, rules with the same name will be overwritten in the process and somehow not executed. I'm thinking of a solution to report the user that there are two rules with the same name, but I'm guessing this should be integrated in the `wdio-cucumber-framework` project.

**Comment by silkentrance** [comment]
Given steps are inherited by scenarios and can also be written as When steps. Declaring them twice as both a Given and a When will result in this error.

So if you need a step both as a Given and a When, simply define it as a Given and use it as a When in your scenario.

**Comment by christian-bromann** [comment]
Thanks for the explanation @silkentrance. I think this can be closed then. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if there are any more questions regarding this.
