### ISSUE TITLE
npm run-script local-webserver Unhandled 'error' event

### ISSUE THREAD

**Issue by aljones15** [webdriverio/cucumber-boilerplate#63]
# Issue description
> Please provide a brief description of the problem you are experiencing

# Steps to reproduce
> How can you reproduce the issue you are facing?
npm run-script local-webserver
# Expected behavior
> What did you expect to happen?
it would start a webserver

# Actual behavior
> What did happen?
threw an error
# Issue occurred on browser/platform 
mac osx 
node v7.2.1
npm 3.10.10

> What platform did you experience this issue on? If you tested multiple browsers/platforms please add them, if you did not experience the issue on other tested browsers or platforms note it as well.

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at doListening (net.js:1397:7)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)

npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run-script" "local-webserver"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! cucumber-boilerplate@1.1.0 local-webserver: `http-server ./demo-app -s`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cucumber-boilerplate@1.1.0 local-webserver script 'http-server ./demo-app -s'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cucumber-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server ./demo-app -s
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cucumber-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cucumber-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrewjones/Documents/codePen/did/darkdiner/integrationTests/cucumber-boilerplate/npm-debug.log

**Comment by aljones15** [comment]
Having a ton of issues btw the fibers package is also throwing build errors during npm install so might be there.

**Comment by aljones15** [comment]
ok changed the port it works now

**Comment by aljones15** [comment]
for future reference in package.json simply change tho port that http-server uses I used http-server -p 4745

**Comment by christian-bromann** [comment]
`Error: listen EADDRINUSE 0.0.0.0:8080` was probably thrown because port 8080 was already used. So yeah in this case you need to change the port in the config.
