### ISSUE TITLE
After following the steps I cannot run tests - 'SupportCode' of undefined

### ISSUE THREAD

**Issue by inspiraller** [webdriverio/cucumber-boilerplate#66]
# Issue description
When following the steps provided in the cucumber readme I cannot run even your default feature tests successfully.

# Steps to reproduce
Pre-requisites - node@6.9.5, npm

1) git clone https://github.com/webdriverio/cucumber-boilerplate.git
2) cd cucumber-boilerplate
3) npm install

Additional step, not included in readme, because this file is missing from package.json:
4) npm install cucumber --save

5) npm run-script local-webserver
6) open new cmd dialog - enter - node_modules\.bin\wdio
to trigger wdio

# Expected behavior
I guess for the tests to run.

# Actual behavior
browsers open, then suddently it crashes with this:
ERROR: Cannot read property 'SupportCode' of undefined

# Issue occurred on browser/platform 
windows 10.

**Comment by inspiraller** [comment]
^2.0.0-rc.7

**Comment by christian-bromann** [comment]
We don't support v2 yet, please install according to https://github.com/webdriverio/wdio-cucumber-framework/blob/master/package.json#L61

**Comment by inspiraller** [comment]
Fantastic. That looks like it worked after doing the following:
$ npm install cucumber@1.3.1 --save

It also asked for this unmet peer dependencies, so I installed that too.
$ npm install eslint-plugin-import@2.2.0 --save

The tests now run perfectly.
brilliant
thanks very much.

**Comment by inspiraller** [comment]
You might want to update your package.json file now to:
```
{
  "name": "cucumber-boilerplate",
  "version": "1.1.0",
  "description": "Boilerplate project to run WebdriverIO tests with Cucumber",
  "homepage": "https://github.com/webdriverio/cucumber-boilerplate",
  "main": "test/runner.js",
  "scripts": {
    "clean": "read -p \"Are you sure you want to clean the project? [y/n] \" -n 1 -r; if [[ $REPLY =~ ^[Yy]$ ]]; then sudo rm -R .git .github demo-app test .travis.yml jest.json wdio.BUILD.conf.js src/features/**; fi",
    "local-webserver": "http-server ./demo-app -s",
    "test": "npm run test:validate && npm run test:unit && npm run test:features",
    "test:features": "npm run-script local-webserver & (wdio wdio.BUILD.conf.js; wdio_ret=$?; kill $(lsof -t -i:8080); exit $wdio_ret)",
    "test:unit": "jest --config=jest.json",
    "test:validate": "eslint 'src/**/*.js' 'test/**/*.js!(setup.js)'"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/webdriverio/cucumber-boilerplate.git"
  },
  "bugs": {
    "url": "https://github.com/webdriverio/cucumber-boilerplate/issues"
  },
  "keywords": [
    "webdriverio",
    "cucumber",
    "test",
    "selenium"
  ],
  "author": "Christian Bromann <christian@saucelabs.com>",
  "license": "MIT",
  "dependencies": {
    "babel-preset-es2015": "~6.18.0",
    "babel-register": "~6.18.0",
    "chai": "~3.5.0",
    "cucumber": "^1.3.1",
    "eslint-plugin-import": "^2.2.0",
    "wdio-cucumber-framework": "~0.2.15",
    "wdio-phantomjs-service": "~0.2.2",
    "wdio-selenium-standalone-service": "~0.0.7",
    "wdio-spec-reporter": "~0.0.5",
    "webdriverio": "~4.6.1"
  },
  "devDependencies": {
    "babel-jest": "~18.0.0",
    "babel-polyfill": "~6.20.0",
    "eslint": "~3.13.1",
    "eslint-config-airbnb-base": "~11.0.1",
    "http-server": "~0.9.0",
    "jest": "~18.1.0"
  }
}

```

regards

**Comment by christian-bromann** [comment]
I think we will move cucumber to be a dependency in `wdio-cucumber-framework` instead of peerDependencies as it seems that peer dependencies aren't installed automatically.

**Comment by wvankuipers** [comment]
Yes that seems to be the issue here, same goes for `eslint-plugin-import` I guess.
