### ISSUE TITLE
Running using tag causes opening empty tabs

### ISSUE THREAD

**Issue by yurii-sorokin** [webdriverio/cucumber-boilerplate#67]
# Issue description
I have few features and glob in specs option like: `specs: [ './src/features/**/*.feature' ]` 
When I try to run tests through wdio cli with `tags` parameter I see that cli executes for each feature, but for features without specified tag it just open browser and close it immediately.

# Issue occurred on browser/platform 
"wdio-cucumber-framework": "^0.2.15",
"webdriverio": "^4.6.2"

**Comment by wvankuipers** [comment]
This is not something that is caused by the boilerplate project but the [wdio-cucumber-framework](https://github.com/webdriverio/wdio-cucumber-framework). There even is an [issue in that repo for this](https://github.com/webdriverio/wdio-cucumber-framework/issues/8).
