### ISSUE TITLE
Support for iteration via templates and placeholders

### ISSUE THREAD

**Issue by inspiraller** [webdriverio/cucumber-boilerplate#68]
Currently there is no solution for iteration. Cucumber-js supports supplying tables for iterating properties.

Example:
https://github.com/cucumber/cucumber/wiki/Scenario-Outlines

**Comment by wvankuipers** [comment]
The scenario outlines support for Cucumber-js should work in the boilerplate out of the box.
Could you send a example of your code that is not working?

**Comment by inspiraller** [comment]
Feature: Test button press
    As a developer
    I want to be able to test if a certain action is performed when a certain
    button is pressed

    # site can be anything...
    Background:
        Given I open the site <brand>
          Examples:
            | brand |
            |  sitex.dev.cwom.co.uk |
            |  sitey.dev.cwom.co.uk |

    Scenario: Test if element responds to button press
        Given the element "#testKeyResponse" not contains any text
        When  I press "a"
        Then  I expect that element "#testKeyResponse" contains the text "65"

**Comment by wvankuipers** [comment]
Ah it won't work this way, try this:

```
Scenario Outline: Test if element responds to button press on site <brand>
    Given I open the site <brand>
    And    the element "#testKeyResponse" not contains any text
    When I press "a"
    Then  I expect that element "#testKeyResponse" contains the text "65"

    Examples:
        | brand |
        |  sitex.dev.cwom.co.uk |
        |  sitey.dev.cwom.co.uk |
```

**Comment by inspiraller** [comment]
Then I have to duplicate that for every scenario, which was the reason for it in the first place.

**Comment by wvankuipers** [comment]
If you want to test all your scenarios using multiple sites I would suggest running wdio multiple times with a different `baseUrl` on each run.
