### ISSUE TITLE
To keep scenarios smaller, we need a beforeAll scenarios solution

### ISSUE THREAD

**Issue by inspiraller** [webdriverio/cucumber-boilerplate#69]
# Issue description
I have a slideshow that has complicated functionality between each slide, but is all within the same url.
Slide 2 will not display until slide 1 has been clicked Next and so forth. If I were to use "Background" to open the url, then each slide I have reached with each scenario would then go back to the start which I don't want.
"Background" runs everytime a scenario is run. 

I need a "beforeAll" method that only every runs once, and then all the scenarios are run, so that I can open a url in my "beforeAll" suite, and all my subsequent scenarios of this feature are within the same url.

**Comment by christian-bromann** [comment]
Please see cucumber hooks: https://github.com/cucumber/cucumber/wiki/Hooks

**Comment by christian-bromann** [comment]
better link: https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/hooks.md
