### ISSUE TITLE
Login step definition missing

### ISSUE THREAD

**Issue by shubhit7** [webdriverio/cucumber-boilerplate#702]
# Issue description
> The Readme.md file have `I log in to site with username "([^"]*)?" and password "([^"]*)?"` as a predefined step definition.
But I could not find its step implementation in `when.ts`.

**Comment by christian-bromann** [comment]
Seems the step is missing. Would you like to send us a PR either removing it from the `README.md` or adding it to the step definition?

**Comment by shubhit7** [comment]
@christian-bromann While I was thinking to add the step definition, I thought it is not straightforward.
We will need the URL, username, password, Username input field, password input field and a login button, so ultimately we need to pass these parameters to query string which will make it bit long and won't look IMO.
Do we have any alternative to this?
Shall we proceed with this approach or remove the query from `README.md` ?

**Comment by christian-bromann** [comment]
> Shall we proceed with this approach or remove the query from `README.md` ?

Sounds good to me 👍

**Comment by shubhit7** [comment]
> > Shall we proceed with this approach or remove the query from `README.md` ?
> 
> Sounds good to me 👍

Removing from README.md ?

**Comment by christian-bromann** [comment]
> Removing from README.md ?

Yes
