### ISSUE TITLE
Block comments do not seem to work properly

### ISSUE THREAD

**Issue by inspiraller** [webdriverio/cucumber-boilerplate#72]
**Example:**
```
Feature: Valuation slide user journey - pre-reqisite
    As a developer
    I want to open the url /valuation/

    Scenario: Background - load url valuation
        Given I open the url "/valuation/"
        Then I expect the url to contain "/valuation/"

"""
 anything here...

"""        
```

**For the above I get an error -** 
1) Background - load url valuation6 I expect the url to contain "/valuation/":
[chrome #0-0] done is not a function

I think the problem is, that cucumber doesn't recognise that it has completed all it's scenarios. The done() method doesn't seem to exist.

**Comment by computamike** [comment]
I thought that comments are three backticks?

**Comment by christian-bromann** [comment]
> [chrome #0-0] done is not a function

This error is because the step definition don't have a done callback compared to the original cucumber step definition. The reason for that is that there is no need for that done function since all methods are synchronous (or in case you use wdio with sync:false it supports promises).
