### ISSUE TITLE
MultiRemote update?

### ISSUE THREAD

**Issue by dandv** [webdriverio/cucumber-boilerplate#8]
The README says MultiRemote was coming soon, and that was before the [v3 update](http://webdriver.io/guide/getstarted/v3.html).

Same for running tests in parallel.

**Comment by christian-bromann** [comment]
mutliremote is available http://webdriver.io/guide/usage/multiremote.html
It just need to get implemented here to run test in parallel.

**Comment by christian-bromann** [comment]
Multiremote was added with recent update
