### ISSUE TITLE
clearInputField Not Working

### ISSUE THREAD

**Issue by jharter** [webdriverio/cucumber-boilerplate#86]
# Issue description
> Please provide a brief description of the problem you are experiencing

I wish to clear a text input field of its text, but it does not remove the tet.

# Steps to reproduce
> How can you reproduce the issue you are facing?

I open a url that contains a text input field containing text. I issue the gherkin command When  I clear the inputfield "//textarea[@id='description']". Never clears the text.

# Expected behavior
> I expected the text in the input field to be cleared.

# Actual behavior
> Field sort of, I think, blinks but does not clear the text.

# Issue occurred on browser/platform 
> Chrome Version 58.0.3029.96 (64-bit)/ MacBook Pro, OS X Yosemite, version 10.10.5

**Comment by jharter** [comment]
I am of the mind that a textarea is a text input field. Is that not the case?

**Comment by christian-bromann** [comment]
@jharter I would recommend to join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.

**Comment by christian-bromann** [comment]
With that I meant that it is not a problem with the boilerplate but rather one with maybe WebdriverIO or Selenium
