### ISSUE TITLE
Possible to have steps not have to specify element vs inputfield?

### ISSUE THREAD

**Issue by cheapsteak** [webdriverio/cucumber-boilerplate#99]
It seems unnecessary as whether the element is an inputfield should be inferable via an element's tagName

One less thing for the BAs to worry about

**Comment by wvankuipers** [comment]
Not quite sure wat you are referring to. You either need to define an element or an input field (which technically is an element) so...

**Comment by cheapsteak** [comment]
Even though an inputfield is an element, you can't write

```
I expect that element "#testKeyResponse" contains the text "65"
```

because the supporting actions are depending on `(element|inputField)` to know `(type !== 'inputfield') ? 'getText' : 'getValue';`

It shouldn't be necessary to specify in the feature whether an element is an "inputfield" or "element", the supporting action should be able to figure that out themselves by the tagName of the element returned after selection, or by checking whether the selected element `'value' in element`

Ideally the step can just be

```
I expect that "#testKeyResponse" contains the text "65"
```

And there's no need for the test writer to know whether the element is an inputfield

**Comment by wvankuipers** [comment]
Good point, I wil implement this is 1.2.0!
